In [86]:
import numpy as np

In [87]:
a1 = np.array([1, 2, 3])

In [88]:
a1

array([1, 2, 3])

In [89]:
type(a1)

numpy.ndarray

In [90]:
a2 = np.array([[1, 2], 
               [3, 4]])

In [91]:
a2

array([[1, 2],
       [3, 4]])

In [97]:
a2.size

4

In [98]:
a4 = np.array([1, 2, 3])
a4

array([1, 2, 3])

In [99]:
import pandas as pd

In [100]:
pd.DataFrame(a4)

0
0  1
1  2
2  3

In [101]:
ones = np.ones((2, 3), int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [102]:
zeros = np.zeros((2, 2), int)
zeros

array([[0, 0],
       [0, 0]])

In [103]:
range_array = np.arange(1, 11, 2)
range_array

array([1, 3, 5, 7, 9])

In [107]:
random_number = np.random.randint(1, 3)
random_number

2

In [108]:
random_matrix = np.random.randint(1, 11, size=(3, 3))
random_matrix

array([[ 3, 10,  4],
       [ 5,  2, 10],
       [ 1,  1,  6]])

In [ ]:
np.random.ra